name: smart_gas_meter_app
description: Smart gas meter monitoring app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  google_fonts: ^8.0.2
  flutter_svg: ^2.2.4
  fl_chart: ^1.1.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo1.svg
    - assets/logos/logo2.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo1.png"
  adaptive_icon_background: "#FFFFFF"